baseURL = "https://christopher-bimson.github.io/"
theme = "LoveIt"
title = "christopher-bimson.github.io"
languageCode = "en"
languageName = "English"

[author]
    name = "Chris"

[outputs]
    home = ["HTML", "RSS", "JSON"]
    
[menu]
    [[menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
    [[menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
    [[menu.main]]
        weight = 3
        identifier = "about"
        pre = ""
        post = ""
        name = "About Me"
        url = "/about/"
        title = ""    

[markup]
    [markup.highlight]
        noClasses = false

[params]
    defaultTheme = "dark"
    title = "christopher-bimson.github.io"
    description = "Technology Leader, Coach, Architect and Software Craftsman"
    images = ["static/android-chrome-192x192.png"]

    [params.app]
        title = "christopher-bimson.github.io"
        noFavicon = false

    [params.header]
        desktopMode = "auto"
        mobileMode = "auto"
            [params.header.title]
            name = "christopher-bimson.github.io"
            typeit = false

    [params.footer]
        enable = true
        hugo = true
        copyright = true
        author = true
        since = 2018
        license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

    [params.section]
        paginate = 20
        dateFormat = "01-02"
        rss = 10

    [params.search]
        enable = true
        type = "lunr"
        contentLength = 4000
        placeholder = "Search..."
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false
    
    [params.home]
        rss = 10
        [params.home.profile]
            enable = true
            avatarURL = "images/avatar-icon.png"
            title = "Christopher Bimson"
            subtitle = "Technology Leader, Coach, Architect and Software Craftsman"
            typeit = true
            social = true
            disclaimer = "Opinions expressed are my own and do not represent my employers past, present or future."
        [params.home.posts]
            enable = true
            paginate = 6
            defaultHiddenFromHomePage = false

    [params.social]
        GitHub = "christopher-bimson"
        Linkedin = "chrisbimson"
        RSS = true

    [params.page]
        hiddenFromHomePage = false
        hiddenFromSearch = false
        twemoji = false
        lightgallery = false
        ruby = true
        fraction = true
        fontawesome = true
        linkToMarkdown = false
        rssFullText = false

        [params.page.toc]
            enable = false
            keepStatic = false
            auto = true

        [params.page.math]
            enable = true
            copyTex = true
            mhchem = true
        
        [params.page.code]
            copy = true
            maxShownLines = 50
            
        [params.page.share]
            enable = true
            Twitter = true
            Facebook = false
            Linkedin = true
            Whatsapp = false
            Pinterest = false
            Tumblr = false
            HackerNews = true
            Reddit = true
            VK = false
            Buffer = false
            Xing = false
            Line = true
            Instapaper = false
            Pocket = false
            Flipboard = false
            Weibo = false
            Blogger = false
            Baidu = false
            Odnoklassniki = false
            Evernote = false
            Skype = false
            Trello = false
            Mix = false

        [params.page.comment]
            enable = false
            
