baseURL = 'http://example.org/'
theme = 'LoveIt'
title = 'My New Hugo Site'
languageCode = 'en'
languageName = 'English'

[author]
    name = 'Christopher Bimson'

[menu]
    [[menu.main]]
        weight = 1
        identifier = 'posts'
        pre = ''
        post = ''
        name = 'Posts'
        url = '/posts/'
        title = ''
    [[menu.main]]
        weight = 2
        identifier = 'tags'
        pre = ''
        post = ''
        name = 'Tags'
        url = '/tags/'
        title = ''
[markup]
    [markup.highlight]
        noClasses = false
    
